# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=180)),
                ('marker', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('karma', models.IntegerField()),
            ],
        ),
    ]
